spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: thuc-tap
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/thuc-tap-database
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

paging:
  default:
    page: 0
    size: 10

logging:
  level:
    org.springframework.cache: error
  file:
    name: logs/trac-nghiem-online.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-file-size: 100MB
      max-history: 7

server:
  port: 3456
